services:
  - type: web
    name: tradutor-profissional-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: tradutor-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: tradutor-db
    databaseName: tradutor
    plan: free
