"""create_initial_tables

Revision ID: eefa6da3aaf0
Revises: 
Create Date: 2024-12-29 15:39:54.284150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eefa6da3aaf0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('preferred_style', sa.JSON(), nullable=True),
    sa.Column('language_pairs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translator_profiles_id'), 'translator_profiles', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('processed_path', sa.String(length=500), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('num_chapters', sa.Integer(), nullable=True),
    sa.Column('total_paragraphs', sa.Integer(), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('translator_profile_id', sa.Integer(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['translator_profile_id'], ['translator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('translated_content', sa.JSON(), nullable=True),
    sa.Column('translation_status', sa.String(length=50), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('formality_level', sa.String(length=20), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('domain_specific', sa.String(length=50), nullable=True),
    sa.Column('preserve_formatting', sa.Boolean(), nullable=True),
    sa.Column('locale_specific', sa.String(length=20), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('revision_needed', sa.Boolean(), nullable=True),
    sa.Column('has_been_edited', sa.Integer(), nullable=True),
    sa.Column('edit_distance', sa.Integer(), nullable=True),
    sa.Column('translator_feedback', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=True),
    sa.Column('learning_flags', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('security_level', sa.String(length=20), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('translator_profile_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['translator_profile_id'], ['translator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_table('translation_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('revised_text', sa.Text(), nullable=False),
    sa.Column('revision_type', sa.String(length=50), nullable=True),
    sa.Column('revision_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('quality_improvement', sa.Float(), nullable=True),
    sa.Column('accepted_changes', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_revisions_id'), 'translation_revisions', ['id'], unique=False)
    op.drop_table('translation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('translated_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('target_language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='translation_pkey')
    )
    op.drop_index(op.f('ix_translation_revisions_id'), table_name='translation_revisions')
    op.drop_table('translation_revisions')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_translator_profiles_id'), table_name='translator_profiles')
    op.drop_table('translator_profiles')
    # ### end Alembic commands ###
